name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Waiting for 200 from the Netlify Preview
        uses: kamranayub/wait-for-netlify-action@2.0.0
        id: wait-for-netflify-preview
        with:
          site_name: "elated-hoover-5c29bf"
        env:
          NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: ${{ steps.wait-for-netflify-preview.outputs.url }}
        with:
          wait-on: ${{ steps.wait-for-netflify-preview.outputs.url }}
          wait-on-timeout: 90