name: Devportal Scraper

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Scraper running
    steps:
    - uses: actions/checkout@v2
    - name: Devportal Scraper
      uses: vtexdocs/devportal-docsearch-action@main
      with:
        algolia_application_id: 'A4TXCBOC74'
        algolia_api_key: ${{ secrets.ALGOLIA_WRITE_KEY }}
        file: './configs/scraper_md.json'
