name: Lighthouse Desktop
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Waiting for pages to change
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-pages-changed
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          checkName: 'Pages changed - elated-hoover-5c29bf'
          timeoutSeconds: 3600
      - name: Waiting for 200 from the Netlify Preview
        if: steps.wait-for-pages-changed.outputs.conclusion == 'neutral'
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: wait-for-netlify-preview
        with:
          site_name: 'elated-hoover-5c29bf'
          max_timeout: 3600
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Select random pages
        id: select-random-pages
        uses: actions/github-script@v6
        env:
          URL: ${{ steps.wait-for-netlify-preview.outputs.url }}
        with:
          script: |
            const { URL } = process.env
            const { selectRandomPages } = require('./src/tests/utils/select-pages.js')
            const pages = selectRandomPages(0.05).map(page => `${URL}/${page}`).join('\n')
            core.setOutput('pages', pages)
            console.log(pages)
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ steps.wait-for-netlify-preview.outputs.url }}
            ${{ steps.select-random-pages.outputs.pages }}
