name: Verify Pull Request Labels

on:
  pull_request:
   types: [opened, reopened, labeled, unlabeled, synchronize]
   branches:
    - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'release-no, release-auto, release-patch, release-minor, release-major'
          invalid-labels: ''
          pull-request-number: '${{ github.event.pull_request.number }}'
